version: '3'

services:
  nginx:
    platform: linux/x86_64
    depends_on:
      - php
    image: nginx
    volumes:
      - /Users/wilf01/Personal/php/php_env/project:/data/php_env/project # 将本地路径映射到容器内（本地路径:容器路径）
      - /Users/wilf01/Personal/php/php_env/nginx_conf:/etc/nginx/conf.d
    restart: always
    ports:
      - 80:80
      - 443:443
    container_name: nginx

  php:
    platform: linux/x86_64
    #    build: . # 编译本地的Dockerfile
    image: hhsh/php-7.1.33 # 编译后的镜像名称（如果build被注释了，则会去docker hub上下载这个镜像）
    depends_on:
      - mysql
      - redis
    restart: always
    volumes:
      - /Users/wilf01/Personal/php/php_env/project:/data/php_env/project
    ports:
      - 9000:9000
    container_name: php

  mysql:
    platform: linux/x86_64
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456 # mysql root用户的密码
    ports:
      - 3306:3306
    container_name: mysql

  redis:
    platform: linux/x86_64
    image: redis
    restart: always
    volumes:
      - /Users/wilf01/Personal/php/php_env/redis_conf/redis.conf:/usr/local/etc/redis/redis.conf
    command:
      redis-server /usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    container_name: redis